- charts/kruise
- versions/0.10.2/.helmignore
- versions/0.10.2/Chart.yaml
- versions/0.10.2/README.md
- versions/0.10.2/ci/default-values.yaml
- versions/0.10.2/templates/_helpers.tpl
- versions/0.10.2/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/0.10.2/templates/apps.kruise.io_broadcastjobs.yaml
- versions/0.10.2/templates/apps.kruise.io_clonesets.yaml
- versions/0.10.2/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/0.10.2/templates/apps.kruise.io_daemonsets.yaml
- versions/0.10.2/templates/apps.kruise.io_imagepulljobs.yaml
- versions/0.10.2/templates/apps.kruise.io_nodeimages.yaml
- versions/0.10.2/templates/apps.kruise.io_sidecarsets.yaml
- versions/0.10.2/templates/apps.kruise.io_statefulsets.yaml
- versions/0.10.2/templates/apps.kruise.io_uniteddeployments.yaml
- versions/0.10.2/templates/apps.kruise.io_workloadspreads.yaml
- versions/0.10.2/templates/manager.yaml
- versions/0.10.2/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/0.10.2/templates/rbac_role.yaml
- versions/0.10.2/templates/webhookconfiguration.yaml
- versions/0.10.2/values.yaml
Signed-off-by: FillZpp <FillZpp.pub@gmail.com>
Package 0.10.2
> Package 0.10.2

- versions/1.0.0-alpha.1/Chart.yaml
- versions/1.0.0-alpha.2/Chart.yaml
- versions/1.0.0-beta.0/Chart.yaml
- versions/1.0.0/Chart.yaml
Signed-off-by: hanshanjie <hanshanjie@meituan.com>
add appVersion for chart to fix https://github.com/openkruise/charts/issues/4
> add appVersion for chart

- charts/kruise
- versions/1.0.1/.helmignore
- versions/1.0.1/Chart.yaml
- versions/1.0.1/README.md
- versions/1.0.1/ci/default-values.yaml
- versions/1.0.1/templates/_helpers.tpl
- versions/1.0.1/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/1.0.1/templates/apps.kruise.io_broadcastjobs.yaml
- versions/1.0.1/templates/apps.kruise.io_clonesets.yaml
- versions/1.0.1/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/1.0.1/templates/apps.kruise.io_daemonsets.yaml
- versions/1.0.1/templates/apps.kruise.io_imagepulljobs.yaml
- versions/1.0.1/templates/apps.kruise.io_nodeimages.yaml
- versions/1.0.1/templates/apps.kruise.io_resourcedistribution.yaml
- versions/1.0.1/templates/apps.kruise.io_sidecarsets.yaml
- versions/1.0.1/templates/apps.kruise.io_statefulsets.yaml
- versions/1.0.1/templates/apps.kruise.io_uniteddeployments.yaml
- versions/1.0.1/templates/apps.kruise.io_workloadspreads.yaml
- versions/1.0.1/templates/manager.yaml
- versions/1.0.1/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/1.0.1/templates/rbac_role.yaml
- versions/1.0.1/templates/webhookconfiguration.yaml
- versions/1.0.1/values.yaml
Signed-off-by: FillZpp <FillZpp.pub@gmail.com>
Note on DCO:
Checklist:
fixes #2 #3 #5
> Add chart 1.0.1

- versions/0.10.2/templates/manager.yaml
- remove useless value
Signed-off-by: hantmac <hantmac@outlook.com>
> remove useless value

- .github/workflows/publish.yaml
Note on DCO:
helm cr upload --skip-existing
> helm cr upload --skip-existing

- charts/kruise
- versions/kruise/1.2.0/.helmignore
- versions/kruise/1.2.0/Chart.yaml
- versions/kruise/1.2.0/README.md
- versions/kruise/1.2.0/ci/default-values.yaml
- versions/kruise/1.2.0/templates/_helpers.tpl
- versions/kruise/1.2.0/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.2.0/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.2.0/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.2.0/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.2.0/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.2.0/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.2.0/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.2.0/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.2.0/templates/apps.kruise.io_resourcedistribution.yaml
- versions/kruise/1.2.0/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.2.0/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.2.0/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.2.0/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.2.0/templates/manager.yaml
- versions/kruise/1.2.0/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.2.0/templates/rbac_role.yaml
- versions/kruise/1.2.0/templates/webhookconfiguration.yaml
- versions/kruise/1.2.0/values.yaml
Signed-off-by: Siyu Wang <FillZpp.pub@gmail.com>
Package chart for v1.2.0
> Package chart for v1.2.0

- charts/kruise-rollout
- versions/kruise-rollout/0.1.1/.helmignore
- versions/kruise-rollout/0.1.1/Chart.yaml
- versions/kruise-rollout/0.1.1/templates/_helpers.tpl
- versions/kruise-rollout/0.1.1/templates/manager.yaml
- versions/kruise-rollout/0.1.1/templates/rbac_role.yaml
- versions/kruise-rollout/0.1.1/templates/rollouts.kruise.io_batchreleases.yaml
- versions/kruise-rollout/0.1.1/templates/rollouts.kruise.io_rollouts.yaml
- versions/kruise-rollout/0.1.1/templates/webhookconfiguration.yaml
- versions/kruise-rollout/0.1.1/values.yaml
> kruise rollout v0.1.1

- charts/kruise-rollout
- versions/kruise-rollout/0.2.0/.helmignore
- versions/kruise-rollout/0.2.0/Chart.yaml
- versions/kruise-rollout/0.2.0/templates/_helpers.tpl
- versions/kruise-rollout/0.2.0/templates/manager.yaml
- versions/kruise-rollout/0.2.0/templates/rbac_role.yaml
- versions/kruise-rollout/0.2.0/templates/rollouts.kruise.io_batchreleases.yaml
- versions/kruise-rollout/0.2.0/templates/rollouts.kruise.io_rollouts.yaml
- versions/kruise-rollout/0.2.0/templates/webhookconfiguration.yaml
- versions/kruise-rollout/0.2.0/values.yaml
> kruise rollout v0.2.0

- charts/kruise
- versions/kruise/1.3.0/.helmignore
- versions/kruise/1.3.0/Chart.yaml
- versions/kruise/1.3.0/README.md
- versions/kruise/1.3.0/ci/default-values.yaml
- versions/kruise/1.3.0/templates/_helpers.tpl
- versions/kruise/1.3.0/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_resourcedistribution.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.3.0/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.3.0/templates/manager.yaml
- versions/kruise/1.3.0/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.3.0/templates/rbac_role.yaml
- versions/kruise/1.3.0/templates/webhookconfiguration.yaml
- versions/kruise/1.3.0/values.yaml
> kruise charts 1.3.0

- charts/kruise-game
- versions/kruise-game/0.1.0/.helmignore
- versions/kruise-game/0.1.0/Chart.yaml
- versions/kruise-game/0.1.0/templates/_helpers.tpl
- versions/kruise-game/0.1.0/templates/game.kruise.io_gameservers.yaml
- versions/kruise-game/0.1.0/templates/game.kruise.io_gameserversets.yaml
- versions/kruise-game/0.1.0/templates/manager.yaml
- versions/kruise-game/0.1.0/templates/rbac_role.yaml
- versions/kruise-game/0.1.0/templates/webhook_service.yaml
- versions/kruise-game/0.1.0/values.yaml
> add chart kruise-game

- versions/kruise-game/0.1.0/templates/controller_manager_config.yaml
- versions/kruise-game/0.1.0/templates/manager.yaml
- versions/kruise-game/0.1.0/templates/rbac_role.yaml
- versions/kruise-game/0.1.0/values.yaml
> add configmap for kruise game

- charts/kruise-rollout
- versions/kruise-rollout/0.3.0-rc.0/.helmignore
- versions/kruise-rollout/0.3.0-rc.0/Chart.yaml
- versions/kruise-rollout/0.3.0-rc.0/templates/_helpers.tpl
- versions/kruise-rollout/0.3.0-rc.0/templates/manager.yaml
- versions/kruise-rollout/0.3.0-rc.0/templates/rbac_role.yaml
- versions/kruise-rollout/0.3.0-rc.0/templates/rollouts.kruise.io_batchreleases.yaml
- versions/kruise-rollout/0.3.0-rc.0/templates/rollouts.kruise.io_rollouthistories.yaml
- versions/kruise-rollout/0.3.0-rc.0/templates/rollouts.kruise.io_rollouts.yaml
- versions/kruise-rollout/0.3.0-rc.0/templates/webhookconfiguration.yaml
- versions/kruise-rollout/0.3.0-rc.0/values.yaml
> kruise rollout v0.3.0-rc.0

- charts/kruise-state-metrics
- versions/kruise-state-metrics/0.1/.helmignore
- versions/kruise-state-metrics/0.1/Chart.yaml
- versions/kruise-state-metrics/0.1/templates/_helpers.tpl
- versions/kruise-state-metrics/0.1/templates/deployment.yaml
- versions/kruise-state-metrics/0.1/templates/service.yaml
- versions/kruise-state-metrics/0.1/templates/serviceaccount.yaml
- versions/kruise-state-metrics/0.1/values.yaml
> kruise state metrics chart

- .github/workflows/publish.yaml
> Modify publish.yaml

- versions/kruise-state-metrics/0.1/Chart.yaml
- versions/kruise-state-metrics/0.1/templates/service.yaml
> kruise state metrics add ServiceMonitor configuration

- charts/kruise
- versions/kruise/1.4/.helmignore
- versions/kruise/1.4/Chart.yaml
- versions/kruise/1.4/README.md
- versions/kruise/1.4/ci/default-values.yaml
- versions/kruise/1.4/templates/_helpers.tpl
- versions/kruise/1.4/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.4/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.4/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.4/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.4/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.4/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.4/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.4/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.4/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.4/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.4/templates/apps.kruise.io_resourcedistribution.yaml
- versions/kruise/1.4/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.4/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.4/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.4/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.4/templates/manager.yaml
- versions/kruise/1.4/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.4/templates/rbac_role.yaml
- versions/kruise/1.4/templates/webhookconfiguration.yaml
- versions/kruise/1.4/values.yaml
> kruise 1.4.0 charts

- charts/kruise-game
- versions/kruise-game/0.2.1/.helmignore
- versions/kruise-game/0.2.1/Chart.yaml
- versions/kruise-game/0.2.1/README.MD
- versions/kruise-game/0.2.1/templates/_helpers.tpl
- versions/kruise-game/0.2.1/templates/controller_manager_config.yaml
- versions/kruise-game/0.2.1/templates/game.kruise.io_gameservers.yaml
- versions/kruise-game/0.2.1/templates/game.kruise.io_gameserversets.yaml
- versions/kruise-game/0.2.1/templates/manager.yaml
- versions/kruise-game/0.2.1/templates/rbac_role.yaml
- versions/kruise-game/0.2.1/templates/webhook_service.yaml
- versions/kruise-game/0.2.1/values.yaml
> kruise-game v0.2.1

- charts/kruise-game
- versions/kruise-game/0.3/.helmignore
- versions/kruise-game/0.3/Chart.yaml
- versions/kruise-game/0.3/README.MD
- versions/kruise-game/0.3/templates/_helpers.tpl
- versions/kruise-game/0.3/templates/alibabacloud.com_poddnats.yaml
- versions/kruise-game/0.3/templates/controller_manager_config.yaml
- versions/kruise-game/0.3/templates/game.kruise.io_gameservers.yaml
- versions/kruise-game/0.3/templates/game.kruise.io_gameserversets.yaml
- versions/kruise-game/0.3/templates/manager.yaml
- versions/kruise-game/0.3/templates/prometheus-monitor.yaml
- versions/kruise-game/0.3/templates/prometheus-service.yaml
- versions/kruise-game/0.3/templates/rbac_role.yaml
- versions/kruise-game/0.3/templates/webhook_service.yaml
- versions/kruise-game/0.3/values.yaml
> kruise game 0.3.0

- charts/kruise-game
- versions/kruise-game/0.4/.helmignore
- versions/kruise-game/0.4/Chart.yaml
- versions/kruise-game/0.4/README.MD
- versions/kruise-game/0.4/templates/_helpers.tpl
- versions/kruise-game/0.4/templates/alibabacloud.com_poddnats.yaml
- versions/kruise-game/0.4/templates/controller_manager_config.yaml
- versions/kruise-game/0.4/templates/game.kruise.io_gameservers.yaml
- versions/kruise-game/0.4/templates/game.kruise.io_gameserversets.yaml
- versions/kruise-game/0.4/templates/manager.yaml
- versions/kruise-game/0.4/templates/prometheus-monitor.yaml
- versions/kruise-game/0.4/templates/prometheus-service.yaml
- versions/kruise-game/0.4/templates/rbac_role.yaml
- versions/kruise-game/0.4/templates/webhook_service.yaml
- versions/kruise-game/0.4/values.yaml
> kruise-game v0.4.0

- versions/kruise-game/0.4/Chart.yaml
- versions/kruise-game/0.4/README.MD
- versions/kruise-game/0.4/values.yaml
> remove dependency

- versions/kruise-game/0.4/values.yaml
> fix chart value

- charts/kruise-game
- versions/kruise-game/0.4.1/.helmignore
- versions/kruise-game/0.4.1/Chart.yaml
- versions/kruise-game/0.4.1/README.MD
- versions/kruise-game/0.4.1/templates/_helpers.tpl
- versions/kruise-game/0.4.1/templates/alibabacloud.com_poddnats.yaml
- versions/kruise-game/0.4.1/templates/controller_manager_config.yaml
- versions/kruise-game/0.4.1/templates/game.kruise.io_gameservers.yaml
- versions/kruise-game/0.4.1/templates/game.kruise.io_gameserversets.yaml
- versions/kruise-game/0.4.1/templates/manager.yaml
- versions/kruise-game/0.4.1/templates/prometheus-monitor.yaml
- versions/kruise-game/0.4.1/templates/prometheus-service.yaml
- versions/kruise-game/0.4.1/templates/rbac_role.yaml
- versions/kruise-game/0.4.1/templates/webhook_service.yaml
- versions/kruise-game/0.4.1/values.yaml
> fix kruise-game 0.4.1

- charts/kruise-rollout
- versions/kruise-rollout/0.4/.helmignore
- versions/kruise-rollout/0.4/Chart.yaml
- versions/kruise-rollout/0.4/README.md
- versions/kruise-rollout/0.4/templates/_helpers.tpl
- versions/kruise-rollout/0.4/templates/manager.yaml
- versions/kruise-rollout/0.4/templates/rbac_role.yaml
- versions/kruise-rollout/0.4/templates/rollouts.kruise.io_batchreleases.yaml
- versions/kruise-rollout/0.4/templates/rollouts.kruise.io_rollouthistories.yaml
- versions/kruise-rollout/0.4/templates/rollouts.kruise.io_rollouts.yaml
- versions/kruise-rollout/0.4/templates/rollouts.kruise.io_trafficroutings.yaml
- versions/kruise-rollout/0.4/templates/webhookconfiguration.yaml
- versions/kruise-rollout/0.4/values.yaml
> kruise rollout v0.4.0

- OWNERS
> add chrisliu1995 as owner

- charts/kruise-game
- versions/kruise-game/0.5/.helmignore
- versions/kruise-game/0.5/Chart.yaml
- versions/kruise-game/0.5/README.MD
- versions/kruise-game/0.5/templates/_helpers.tpl
- versions/kruise-game/0.5/templates/alibabacloud.com_poddnats.yaml
- versions/kruise-game/0.5/templates/controller_manager_config.yaml
- versions/kruise-game/0.5/templates/game.kruise.io_gameservers.yaml
- versions/kruise-game/0.5/templates/game.kruise.io_gameserversets.yaml
- versions/kruise-game/0.5/templates/manager.yaml
- versions/kruise-game/0.5/templates/prometheus-monitor.yaml
- versions/kruise-game/0.5/templates/prometheus-service.yaml
- versions/kruise-game/0.5/templates/rbac_role.yaml
- versions/kruise-game/0.5/templates/webhook_service.yaml
- versions/kruise-game/0.5/values.yaml
> kruise-game v0.5.0

- versions/kruise/1.4/1.5
> Remove unwelcome softlink

- versions/kruise/1.5/templates/apps.kruise.io_clonesets.yaml
> modify kruise v1.5.0 cloneset yaml

- versions/kruise/1.5/values.yaml
> reload kruise v1.5.0 chart

- charts/kruise-game
- versions/kruise-game/0.6/.helmignore
- versions/kruise-game/0.6/Chart.yaml
- versions/kruise-game/0.6/README.MD
- versions/kruise-game/0.6/templates/_helpers.tpl
- versions/kruise-game/0.6/templates/alibabacloud.com_poddnats.yaml
- versions/kruise-game/0.6/templates/controller_manager_config.yaml
- versions/kruise-game/0.6/templates/game.kruise.io_gameservers.yaml
- versions/kruise-game/0.6/templates/game.kruise.io_gameserversets.yaml
- versions/kruise-game/0.6/templates/manager.yaml
- versions/kruise-game/0.6/templates/prometheus-monitor.yaml
- versions/kruise-game/0.6/templates/prometheus-service.yaml
- versions/kruise-game/0.6/templates/rbac_role.yaml
- versions/kruise-game/0.6/templates/webhook_service.yaml
- versions/kruise-game/0.6/values.yaml
> kruise-game v0.6.0

- charts/kruise
- versions/kruise/1.5.1/.helmignore
- versions/kruise/1.5.1/Chart.yaml
- versions/kruise/1.5.1/README.md
- versions/kruise/1.5.1/ci/default-values.yaml
- versions/kruise/1.5.1/templates/_helpers.tpl
- versions/kruise/1.5.1/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_imagelistpulljobs.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_resourcedistribution.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.5.1/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.5.1/templates/manager.yaml
- versions/kruise/1.5.1/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.5.1/templates/rbac_role.yaml
- versions/kruise/1.5.1/templates/webhookconfiguration.yaml
- versions/kruise/1.5.1/values.yaml
> openkruise charts v1.5.1

- charts/kruise
- versions/kruise/1.5.2/.helmignore
- versions/kruise/1.5.2/Chart.yaml
- versions/kruise/1.5.2/README.md
- versions/kruise/1.5.2/ci/default-values.yaml
- versions/kruise/1.5.2/templates/_helpers.tpl
- versions/kruise/1.5.2/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_imagelistpulljobs.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_resourcedistribution.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.5.2/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.5.2/templates/manager.yaml
- versions/kruise/1.5.2/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.5.2/templates/rbac_role.yaml
- versions/kruise/1.5.2/templates/webhookconfiguration.yaml
- versions/kruise/1.5.2/values.yaml
> krusie 1.5.2

- versions/kruise/1.4.1/.helmignore
- versions/kruise/1.4.1/Chart.yaml
- versions/kruise/1.4.1/README.md
- versions/kruise/1.4.1/ci/default-values.yaml
- versions/kruise/1.4.1/templates/_helpers.tpl
- versions/kruise/1.4.1/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_resourcedistribution.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.4.1/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.4.1/templates/manager.yaml
- versions/kruise/1.4.1/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.4.1/templates/rbac_role.yaml
- versions/kruise/1.4.1/templates/webhookconfiguration.yaml
- versions/kruise/1.4.1/values.yaml
> kruise 1.4.1

- charts/kruise
- versions/kruise/1.3.1/.helmignore
- versions/kruise/1.3.1/Chart.yaml
- versions/kruise/1.3.1/README.md
- versions/kruise/1.3.1/ci/default-values.yaml
- versions/kruise/1.3.1/templates/_helpers.tpl
- versions/kruise/1.3.1/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_resourcedistribution.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.3.1/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.3.1/templates/manager.yaml
- versions/kruise/1.3.1/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.3.1/templates/rbac_role.yaml
- versions/kruise/1.3.1/templates/webhookconfiguration.yaml
- versions/kruise/1.3.1/values.yaml
> kruise 1.3.1

- charts/kruise
- versions/kruise/1.6.0/.helmignore
- versions/kruise/1.6.0/Chart.yaml
- versions/kruise/1.6.0/README.md
- versions/kruise/1.6.0/ci/default-values.yaml
- versions/kruise/1.6.0/templates/_helpers.tpl
- versions/kruise/1.6.0/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_imagelistpulljobs.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_resourcedistributions.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.6.0/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.6.0/templates/manager.yaml
- versions/kruise/1.6.0/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.6.0/templates/rbac_role.yaml
- versions/kruise/1.6.0/templates/webhookconfiguration.yaml
- versions/kruise/1.6.0/values.yaml
> kruise 1.6.0

- charts/kruise
- versions/kruise/1.5.3/.helmignore
- versions/kruise/1.5.3/Chart.yaml
- versions/kruise/1.5.3/README.md
- versions/kruise/1.5.3/ci/default-values.yaml
- versions/kruise/1.5.3/templates/_helpers.tpl
- versions/kruise/1.5.3/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_imagelistpulljobs.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_resourcedistribution.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.5.3/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.5.3/templates/manager.yaml
- versions/kruise/1.5.3/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.5.3/templates/rbac_role.yaml
- versions/kruise/1.5.3/templates/webhookconfiguration.yaml
- versions/kruise/1.5.3/values.yaml
> kruise 1.5.3

- charts/kruise
- versions/kruise/1.6.1/.helmignore
- versions/kruise/1.6.1/Chart.yaml
- versions/kruise/1.6.1/README.md
- versions/kruise/1.6.1/ci/default-values.yaml
- versions/kruise/1.6.1/templates/_helpers.tpl
- versions/kruise/1.6.1/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_imagelistpulljobs.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_resourcedistributions.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.6.1/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.6.1/templates/manager.yaml
- versions/kruise/1.6.1/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.6.1/templates/rbac_role.yaml
- versions/kruise/1.6.1/templates/webhookconfiguration.yaml
- versions/kruise/1.6.1/values.yaml
> kruise 1.6.1

- charts/kruise
- versions/kruise/1.4.2/.helmignore
- versions/kruise/1.4.2/Chart.yaml
- versions/kruise/1.4.2/README.md
- versions/kruise/1.4.2/ci/default-values.yaml
- versions/kruise/1.4.2/templates/_helpers.tpl
- versions/kruise/1.4.2/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_resourcedistribution.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.4.2/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.4.2/templates/manager.yaml
- versions/kruise/1.4.2/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.4.2/templates/rbac_role.yaml
- versions/kruise/1.4.2/templates/webhookconfiguration.yaml
- versions/kruise/1.4.2/values.yaml
> kruise 1.4.2

- charts/kruise
- versions/kruise/1.5.4/.helmignore
- versions/kruise/1.5.4/Chart.yaml
- versions/kruise/1.5.4/README.md
- versions/kruise/1.5.4/ci/default-values.yaml
- versions/kruise/1.5.4/templates/_helpers.tpl
- versions/kruise/1.5.4/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_imagelistpulljobs.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_resourcedistribution.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.5.4/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.5.4/templates/manager.yaml
- versions/kruise/1.5.4/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.5.4/templates/rbac_role.yaml
- versions/kruise/1.5.4/templates/webhookconfiguration.yaml
- versions/kruise/1.5.4/values.yaml
> kruise 1.5.4

- charts/kruise
- versions/kruise/1.6.2/.helmignore
- versions/kruise/1.6.2/Chart.yaml
- versions/kruise/1.6.2/README.md
- versions/kruise/1.6.2/ci/default-values.yaml
- versions/kruise/1.6.2/templates/_helpers.tpl
- versions/kruise/1.6.2/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_imagelistpulljobs.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_resourcedistributions.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.6.2/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.6.2/templates/manager.yaml
- versions/kruise/1.6.2/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.6.2/templates/rbac_role.yaml
- versions/kruise/1.6.2/templates/webhookconfiguration.yaml
- versions/kruise/1.6.2/values.yaml
> krusie 1.6.2

- charts/kruise
- versions/kruise/1.6.3/.helmignore
- versions/kruise/1.6.3/Chart.yaml
- versions/kruise/1.6.3/README.md
- versions/kruise/1.6.3/ci/default-values.yaml
- versions/kruise/1.6.3/templates/_helpers.tpl
- versions/kruise/1.6.3/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_imagelistpulljobs.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_resourcedistributions.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.6.3/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.6.3/templates/manager.yaml
- versions/kruise/1.6.3/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.6.3/templates/rbac_role.yaml
- versions/kruise/1.6.3/templates/webhookconfiguration.yaml
- versions/kruise/1.6.3/values.yaml
> kruise 1.6.3

- charts/kruise-game
- versions/kruise-game/0.8/.helmignore
- versions/kruise-game/0.8/Chart.yaml
- versions/kruise-game/0.8/README.md
- versions/kruise-game/0.8/templates/_helpers.tpl
- versions/kruise-game/0.8/templates/alibabacloud.com_poddnats.yaml
- versions/kruise-game/0.8/templates/controller_manager_config.yaml
- versions/kruise-game/0.8/templates/game.kruise.io_gameservers.yaml
- versions/kruise-game/0.8/templates/game.kruise.io_gameserversets.yaml
- versions/kruise-game/0.8/templates/manager.yaml
- versions/kruise-game/0.8/templates/prometheus-monitor.yaml
- versions/kruise-game/0.8/templates/rbac_role.yaml
- versions/kruise-game/0.8/templates/scaler-service.yaml
- versions/kruise-game/0.8/templates/webhook_service.yaml
- versions/kruise-game/0.8/values.yaml
> Add kruise game 0.8

- charts/kruise
- versions/kruise/1.7.0-alphal.1/.helmignore
- versions/kruise/1.7.0-alphal.1/Chart.yaml
- versions/kruise/1.7.0-alphal.1/README.md
- versions/kruise/1.7.0-alphal.1/ci/default-values.yaml
- versions/kruise/1.7.0-alphal.1/templates/_helpers.tpl
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_imagelistpulljobs.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_resourcedistributions.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.7.0-alphal.1/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.7.0-alphal.1/templates/manager.yaml
- versions/kruise/1.7.0-alphal.1/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.7.0-alphal.1/templates/rbac_role.yaml
- versions/kruise/1.7.0-alphal.1/templates/webhookconfiguration.yaml
- versions/kruise/1.7.0-alphal.1/values.yaml
> kruise 1.7.0-alphal.1

- charts/kruise-game
- versions/kruise-game/0.9/.helmignore
- versions/kruise-game/0.9/Chart.yaml
- versions/kruise-game/0.9/README.md
- versions/kruise-game/0.9/templates/_helpers.tpl
- versions/kruise-game/0.9/templates/alibabacloud.com_poddnats.yaml
- versions/kruise-game/0.9/templates/controller_manager_config.yaml
- versions/kruise-game/0.9/templates/game.kruise.io_gameservers.yaml
- versions/kruise-game/0.9/templates/game.kruise.io_gameserversets.yaml
- versions/kruise-game/0.9/templates/manager.yaml
- versions/kruise-game/0.9/templates/prometheus-monitor.yaml
- versions/kruise-game/0.9/templates/rbac_role.yaml
- versions/kruise-game/0.9/templates/scaler-service.yaml
- versions/kruise-game/0.9/templates/webhook_service.yaml
- versions/kruise-game/0.9/values.yaml
> kruise game 0.9.0

- charts/kruise
- versions/kruise/1.7.1/.helmignore
- versions/kruise/1.7.1/Chart.yaml
- versions/kruise/1.7.1/README.md
- versions/kruise/1.7.1/ci/default-values.yaml
- versions/kruise/1.7.1/templates/_helpers.tpl
- versions/kruise/1.7.1/templates/apps.kruise.io_advancedcronjobs.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_broadcastjobs.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_clonesets.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_containerrecreaterequests.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_daemonsets.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_imagelistpulljobs.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_imagepulljobs.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_nodeimages.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_nodepodprobes.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_persistentpodstates.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_podprobemarkers.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_resourcedistributions.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_sidecarsets.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_statefulsets.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_uniteddeployments.yaml
- versions/kruise/1.7.1/templates/apps.kruise.io_workloadspreads.yaml
- versions/kruise/1.7.1/templates/manager.yaml
- versions/kruise/1.7.1/templates/policy.kruise.io_podunavailablebudgets.yaml
- versions/kruise/1.7.1/templates/rbac_role.yaml
- versions/kruise/1.7.1/templates/webhookconfiguration.yaml
- versions/kruise/1.7.1/values.yaml
> kruise 1.7.1

- charts/kruise
> build kruise 1.6.4 charts

- charts/kruise
> build kruise 1.7.2 charts

- .github/workflows/lint-and-test.yml
- charts/kruise-game
- versions/kruise-game/0.10/.helmignore
- versions/kruise-game/0.10/Chart.yaml
- versions/kruise-game/0.10/README.md
- versions/kruise-game/0.10/templates/_helpers.tpl
- versions/kruise-game/0.10/templates/controller_manager_config.yaml
- versions/kruise-game/0.10/templates/game.kruise.io_gameservers.yaml
- versions/kruise-game/0.10/templates/game.kruise.io_gameserversets.yaml
- versions/kruise-game/0.10/templates/manager.yaml
- versions/kruise-game/0.10/templates/prometheus-monitor.yaml
- versions/kruise-game/0.10/templates/rbac_role.yaml
- versions/kruise-game/0.10/templates/scaler-service.yaml
- versions/kruise-game/0.10/templates/webhook_service.yaml
- versions/kruise-game/0.10/values.yaml
> kruise game 0.10.0

- versions/kruise-rollout/0.3/templates/webhookconfiguration.yaml
- versions/kruise-rollout/0.6.0/templates/webhookconfiguration.yaml
- versions/kruise-rollout/0.6.1/templates/webhookconfiguration.yaml
> Chore: reformat rollout chart

- versions/kruise-rollout/0.4.3/.helmignore
- versions/kruise-rollout/0.4.3/Chart.yaml
- versions/kruise-rollout/0.4.3/README.md
- versions/kruise-rollout/0.4.3/templates/_helpers.tpl
- versions/kruise-rollout/0.4.3/templates/manager.yaml
- versions/kruise-rollout/0.4.3/templates/rbac_role.yaml
- versions/kruise-rollout/0.4.3/templates/rollouts.kruise.io_batchreleases.yaml
- versions/kruise-rollout/0.4.3/templates/rollouts.kruise.io_rollouthistories.yaml
- versions/kruise-rollout/0.4.3/templates/rollouts.kruise.io_rollouts.yaml
- versions/kruise-rollout/0.4.3/templates/rollouts.kruise.io_trafficroutings.yaml
- versions/kruise-rollout/0.4.3/templates/webhookconfiguration.yaml
- versions/kruise-rollout/0.4.3/values.yaml
- versions/kruise-rollout/0.5.2/.helmignore
- versions/kruise-rollout/0.5.2/Chart.yaml
- versions/kruise-rollout/0.5.2/README.md
- versions/kruise-rollout/0.5.2/templates/_helpers.tpl
- versions/kruise-rollout/0.5.2/templates/manager.yaml
- versions/kruise-rollout/0.5.2/templates/rbac_role.yaml
- versions/kruise-rollout/0.5.2/templates/rollouts.kruise.io_batchreleases.yaml
- versions/kruise-rollout/0.5.2/templates/rollouts.kruise.io_rollouthistories.yaml
- versions/kruise-rollout/0.5.2/templates/rollouts.kruise.io_rollouts.yaml
- versions/kruise-rollout/0.5.2/templates/rollouts.kruise.io_trafficroutings.yaml
- versions/kruise-rollout/0.5.2/templates/webhookconfiguration.yaml
- versions/kruise-rollout/0.5.2/values.yaml
> Release: rollout v0.5.2 and v0.4.3
